### ISSUE TITLE
sudohide v. 1.20 and above crashes on KitKat

### ISSUE THREAD

**Issue by Diversant1987** [SudoCode755/SudoHide#5]
10-23 16:17:13.836 V/ApplicationPolicy(3314): isApplicationStateBlocked userId 0 pkgname com.sudocode.sudohide
10-23 16:17:13.916 D/Prevent (3314): allow start activity com.sudocode.sudohide/.MainActivity
10-23 16:17:13.991 V/Prevent (3314): launch, current: [com.sudocode.sudohide]
10-23 16:17:13.991 D/Prevent (3314): action: start activity, package: com.sudocode.sudohide, count: 1
10-23 16:17:18.731 D/Prevent (3314): action: user leaving activity , package: com.sudocode.sudohide, count: 1
10-23 16:17:19.296 E/ActivityThread(1102): Performing stop of activity that is not resumed: {com.sudocode.sudohide/com.sudocode.sudohide.MainActivity}
10-23 16:17:19.296 E/ActivityThread(1102): java.lang.RuntimeException: Performing stop of activity that is not resumed: {com.sudocode.sudohide/com.sudocode.sudohide.MainActivity}
10-23 16:17:37.416 I/dalvikvm(1102):   at com.sudocode.sudohide.Adapters.AppListGetter.getAppsFromPM(AppListGetter.java:50)
10-23 16:17:37.421 I/dalvikvm(1102):   at com.sudocode.sudohide.Adapters.AppListGetter.doInBackground(AppListGetter.java:92)
10-23 16:17:37.421 I/dalvikvm(1102):   at com.sudocode.sudohide.Adapters.AppListGetter.doInBackground(AppListGetter.java:18)
10-23 16:17:39.311 I/ActivityManager(3314): Process com.sudocode.sudohide (pid 1102) (adj 11) has died.
10-23 16:17:39.316 D/Prevent (3314): action: app died, package: com.sudocode.sudohide--com.sudocode.sudohide, count: 0
10-23 16:17:43.511 D/Prevent (3314): checking services, packages: [com.sudocode.sudohide], whitelist: [com.google.android.gms, com.google.android.gsf, com.google.android.gsf.login]

**Comment by Diversant1987** [comment]
logs from v. 1.28:
10-23 20:48:15.723 V/ApplicationPolicy(31216): isApplicationStateBlocked userId 0 pkgname com.sudocode.sudohide
10-23 20:48:15.828 D/Prevent (31216): allow start activity com.sudocode.sudohide/.MainActivity
10-23 20:48:15.868 D/Prevent (31216): allow start activity com.sudocode.sudohide/.MainActivity
10-23 20:48:15.878 V/Prevent (31216): launch, current: [com.sudocode.sudohide]
10-23 20:48:15.878 V/Prevent (31216): pid 4235 is not for com.sudocode.sudohide
10-23 20:48:15.878 D/Prevent (31216): action: start activity, package: com.sudocode.sudohide, count: 1
10-23 20:48:32.913 I/dalvikvm(7808):   at com.sudocode.sudohide.Adapters.AppListGetter.getAppsFromPM(AppListGetter.java:50)
10-23 20:48:32.913 I/dalvikvm(7808):   at com.sudocode.sudohide.Adapters.AppListGetter.doInBackground(AppListGetter.java:92)
10-23 20:48:32.913 I/dalvikvm(7808):   at com.sudocode.sudohide.Adapters.AppListGetter.doInBackground(AppListGetter.java:18)
10-23 20:48:32.943 E/AndroidRuntime(7808): Process: com.sudocode.sudohide, PID: 7808
10-23 20:48:32.943 E/AndroidRuntime(7808): 	at com.sudocode.sudohide.Adapters.AppListGetter.getAppsFromPM(AppListGetter.java:50)
10-23 20:48:32.943 E/AndroidRuntime(7808): 	at com.sudocode.sudohide.Adapters.AppListGetter.doInBackground(AppListGetter.java:92)
10-23 20:48:32.943 E/AndroidRuntime(7808): 	at com.sudocode.sudohide.Adapters.AppListGetter.doInBackground(AppListGetter.java:18)
10-23 20:48:32.953 W/ActivityManager(31216):   Force finishing activity com.sudocode.sudohide/.MainActivity
10-23 20:48:33.268 V/Prevent (31216): resume, current: [com.sec.android.app.launcher, com.sudocode.sudohide]
10-23 20:48:33.923 D/Prevent (31216): action: destroy activity, package: com.sudocode.sudohide, count: 0
10-23 20:48:33.928 D/Prevent (31216): action: destroy activity, will force stop com.sudocode.sudohide if needed in 6s
10-23 20:48:34.003 E/WindowManager(7808): android.view.WindowLeaked: Activity com.sudocode.sudohide.MainActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{43688dd8 V.E..... R......D 0,0-684,211} that was originally added here
10-23 20:48:34.003 E/WindowManager(7808): 	at com.sudocode.sudohide.Adapters.AppListGetter.onPreExecute(AppListGetter.java:83)
10-23 20:48:34.003 E/WindowManager(7808): 	at com.sudocode.sudohide.Adapters.AppListGetter.getInstance(AppListGetter.java:40)
10-23 20:48:34.003 E/WindowManager(7808): 	at com.sudocode.sudohide.Adapters.AppListAdapter.<init>(AppListAdapter.java:28)
10-23 20:48:34.003 E/WindowManager(7808): 	at com.sudocode.sudohide.Adapters.MainAdapter.<init>(MainAdapter.java:26)
10-23 20:48:34.003 E/WindowManager(7808): 	at com.sudocode.sudohide.MainActivity.onCreate(MainActivity.java:47)
10-23 20:48:35.803 D/Prevent (31216): action: app died, package: com.sudocode.sudohide--com.sudocode.sudohide, count: 0
10-23 20:48:35.803 I/ActivityManager(31216): Process com.sudocode.sudohide (pid 7808) (adj 9) has died.
10-23 20:48:39.928 D/Prevent (31216): checking services, packages: [com.sudocode.sudohide], whitelist: [com.google.android.gms, com.google.android.gsf, com.google.android.gsf.login]
